[testtop]
l2_sets = 64
l2_ways = 8
l2_banks = 1
# l3cdir_sets should be greater than l2_sets * l2_banks
l3cdir_sets = 128 
l3cdir_ways = 6

l3_sets = 512
l3_ways = 8
l3_banks = 1

[nemu]
mode = CORE_ALONE

[matrix]
m = 64
k = 256
n = 128

[tltest]
l1_sets = 32
l1_ways = 8
